### ISSUE TITLE
Show proper error when git config is not set

### ISSUE THREAD

**Issue by nirav24** [geongeorge/Git-User-Switch#11]
I was setting up a new machine and I didn't set up git user/email and tried to run `git-user` which threw the below error.

```
(node:9559) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of null
    at initUser (/usr/local/lib/node_modules/git-user-switch/src/lib/initUser.js:13:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/usr/local/lib/node_modules/git-user-switch/src/cli.js:58:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9559) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9559) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

it might be better to show some error message with clarification.

**Comment by geongeorge** [comment]
Hey @nirav24 Thanks for reporting. Should be fixed by https://github.com/geongeorge/Git-User-Switch/pull/12
and in `git-user-switch@0.5.0` can you confirm?
